name: Verify

on:
  pull_request_target:
    branches:
      - develop
      - master

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: Install the dependencies
        run: npm ci
      - name: Check formatting
        run: npm run check-fmt
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: Install the dependencies
        run: npm ci
      - name: Lint source code
        run: npm run lint
